-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohTable1 = {
	["Charge"] = 1,
	["Action"] = "Spike",
	["SpecialCharge"] = 0.9921694838188317,
	["TiltDirection"] = 0, 1, 0,
	["BallId"] = 72746008624,
	["MoveDirection"] = -0.0534561425447464, 1.4456306018928444e-07, -0.9985702037811279,
	["From"] = "Client",
	["HitboxSize"] = 7.5, 8.904999732971191, 6.4710001945495605,
	["LookVector"] = -0.9995639324188232, -9.726828409384325e-08, 0.029528645798563957
}

game:GetService("ReplicatedStorage").Packages._Index["sleitnick_knit@1.7.0"].knit.Services.BallService.RF.Interact:InvokeServer(ohTable1)


local function rotateTowardsXZ(lookVector, tiltVector, maxAngleDegrees)
	local lookXZ = Vector3.new(lookVector.X, 0, lookVector.Z)
	local tiltXZ = Vector3.new(tiltVector.X, 0, tiltVector.Z)

	if lookXZ.Magnitude == 0 or tiltXZ.Magnitude == 0 then
		return lookVector
	end

	lookXZ = lookXZ.Unit
	tiltXZ = tiltXZ.Unit

	local dot = lookXZ:Dot(tiltXZ)
	local angle = math.acos(math.clamp(dot, -1, 1))

	if math.deg(angle) <= maxAngleDegrees then
		return Vector3.new(tiltVector.X, lookVector.Y, tiltVector.Z).Unit
	end

	local cross = lookXZ:Cross(tiltXZ).Y
	local direction = if cross >= 0 then 1 else -1

	local angleToRotate = math.rad(maxAngleDegrees) * direction

	local rotatedXZ = (CFrame.Angles(0, angleToRotate, 0) * lookXZ)

	return Vector3.new(rotatedXZ.X, lookVector.Y, rotatedXZ.Z).Unit
end

local ENABLED = true
local MAX_ANGLE = 45

local old;
old = hookmetamethod(game, "__namecall", newcclosure(function(self, ...)
    local args = {...}
    if  not checkcaller() then
        if getnamecallmethod() == "InvokeServer" and typeof(self) == "Instance" and self.ClassName == "RemoteFunction" and self.Name == "Interact" then
            local t = args[1]
            if typeof(t) == "table" and rawget(t, "Action") == "Spike" and rawget(t, "LookVector") ~= nil and rawget(t, "TiltDirection") ~= nil then
                local lookVector = rotateTowardsXZ(rawget(t, "LookVector"), rawget(t, "TiltDirection"), MAX_ANGLE)
                rawset(t, "LookVector", lookVector)
            end
        end
    end
    return old(self, table.unpack(args))
end))